name: Deploy Results API
on:
  push:
    branches: [deploy]
  workflow_dispatch:
  
jobs:
  build:
    name: Build Results
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.4'
      
      - name: Build
        run: go build .

      - name: Copying files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "results"
          target: "deploy"