name: Deploy Results API
on:
  push:
    branches: [deploy]
  workflow_dispatch:
  
jobs:
  build:
    name: Build Results
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.21.6'
          check-latest: true
      - name: Build
        run: go build .

      - name: Copying files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "results"
          target: "deploy"